# Moving the configs to the top and referencing elsewhere is a
# workaround for Ansible's hash_behaviour settings
control_center_config:
  confluent.controlcenter.command.topic.replication: 3
  confluent.controlcenter.internal.topics.replication: 3
  confluent.metrics.topic.replication: 3
  confluent.monitoring.interceptor.topic.replication: 3

confluent:
  control:
    center:
      user: cp-control-center
      group: confluent
      config_file: /etc/confluent-control-center/control-center-production.properties
      service_name: confluent-control-center
      systemd_override: /etc/systemd/system/confluent-control-center.service.d
      environment:
        CONTROL_CENTER_HEAP_OPTS: "-Xmx6g"
      config:
        confluent.controlcenter.streams.num.stream.threads: 8
        confluent.controlcenter.data.dir: /var/lib/confluent/control-center
        confluent.controlcenter.ksql.enable: 'true'
        confluent.controlcenter.schema.registry.enable: 'true'
        confluent.controlcenter.streams.ssl.endpoint.identification.algorithm: ""
        confluent.controlcenter.rest.ssl.endpoint.identification.algorithm: ""
        confluent.controlcenter.command.topic.replication: "{{ control_center_config['confluent.controlcenter.command.topic.replication'] }}"
        confluent.controlcenter.internal.topics.replication: "{{ control_center_config['confluent.controlcenter.internal.topics.replication'] }}"
        confluent.metrics.topic.replication: "{{ control_center_config['confluent.metrics.topic.replication'] }}"
        confluent.monitoring.interceptor.topic.replication: "{{ control_center_config['confluent.monitoring.interceptor.topic.replication'] }}"
      systemd:
        enabled: yes
        state: started
